### ISSUE TITLE
Is compatible with DNS Server?

### ISSUE THREAD

**Issue by Rihan9** [newsnowlabs/docker-ingress-routing-daemon#11]
Hi,
first of all, thank you so much for your work.
I am using your script for my reverse proxy inside a docker swarm with success, but I can't get it to work whenI try to use it for DNS server as well.

I run your script with the following line inside a systemctl service:
```
docker-ingress-routing-daemon --install --ingress-gateway-ips 10.0.0.2 --services sh_adguardhome,sh_nginx-proxy-manager --udp-ports 53,853,80,443,67,68 --tcp-ports 53,853,80,443,67,68
```

sh_nginx-proxy-manager -> this works well (ports 80 and 443)
sh_adguardhome --> this not works (ports 53,83,67 and 68).

Currently, I'm using host mode and Placement constraints to run the service in the same server of load balancing to get it works. It works also in ingress mode, but without the correct Ip all the dns requests come from the same ip address making monitoring impossible (I don't want to violate user privacy, I need to know if any network devices are doing weird things). Following the current service compose:

```
adguardhome:
  image: adguard/adguardhome:latest
  networks:
    - raspberry_network
  ports:
    # - 53:53/udp
    - target: 53
      published: 53
      protocol: udp
      mode: host
    # - 53:53/tcp
    - target: 53
      published: 53
      protocol: tcp
      mode: host
    # - 853:853/udp
    - target: 853
      published: 853
      protocol: udp
      mode: host
    # - 853:853/tcp
    - target: 853
      published: 853
      protocol: tcp
      mode: host
    # - 67:67/udp
    - target: 67
      published: 67
      protocol: udp
      mode: host
    # - 67:67/tcp
    - target: 67
      published: 67
      protocol: tcp
      mode: host
    # - 68:68/udp
    - target: 68
      published: 68
      protocol: udp
      mode: host
    # - 68:68/tcp
    - target: 68
      published: 68
      protocol: tcp
      mode: host
  volumes:
    - /media/gfs/adguardhome_conf:/opt/adguardhome/conf
    - /media/gfs/adguardhome_work:/opt/adguardhome/work
```

the most common response on dns request is: DNS_PROBE_STARTED followed by DNS_PROBE_FINISHED_BAD_CONFIG.

With wireshark I made a communication log. I see that the server has responded, but its source address is not that of the load-balancer or host. The address appears to be the one inside the ingress network . Is it possible that this is why it fails?
![image](https://user-images.githubusercontent.com/33684020/122027294-4aaf7500-cdcb-11eb-9b26-c049cfd0061c.png)
